apiVersion: v1
kind: Service
metadata:
  name: carpooling-rest-blocking
spec:
  type: LoadBalancer
  selector:
   app: carpooling-rest-blocking
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
      name: http