apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
      labels:
        app: routing-service
    spec:
      containers:
        - name: routing-service
          image: registry.gitlab.com/tech-commuting/carpooling-rest:0.0.3-routing-service
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: JAVA_TOOL_OPTIONS
              value: " -Xmx512m -Xms256m"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              cpu: "100m"
              memory: "256m"
          ports:
            - name: web
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: web
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: web
            initialDelaySeconds: 90
      imagePullSecrets:
        - name: registry.gitlab.com