apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: carpooling-rest
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/actuator/prometheus'
      labels:
        app: carpooling-rest
    spec:
      containers:
        - name: carpooling-rest
          image: registry.gitlab.com/tech-commuting/carpooling-rest:0.0.7-reactive
          #image: registry.gitlab.com/tech-commuting/carpooling-rest:0.0.3-blocking
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/rest-perf
            - name: SERVER_PORT
              value: "8080"
            - name: JAVA_TOOL_OPTIONS
              value: " -Xmx512m -Xms256m"
            - name: ROUTING_API_URL
              value: "http://routing-service:8080"
            #- name: SPRING_PROFILES_ACTIVE
            #  value: "perf"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              cpu: "100m"
              memory: "512Mi"
          ports:
            - name: web
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: web
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: web
            initialDelaySeconds: 180
      imagePullSecrets:
        - name: registry.gitlab.com